version: '3.1'

services:

  nestjs-project-api:
    container_name: dockerization-nestjs-projec
    build: . #build Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/nestjs-project-api # the volume mirrors the sources into the container so it catches development changes
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: postgres-db
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
